version: 2

project_name: correlic-backend

builds:
  - id: api
    main: ./cmd/api
    binary: correlic-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: telemetry
    main: ./cmd/telemetry
    binary: correlic-telemetry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: admin
    main: ./cmd/admin
    binary: correlic-admin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - migrations/**/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: Correlic
    name: correlic-backend
  draft: true
