//go:build linux

// Package ebpf provides eBPF-based process execution monitoring.
//
// 🎓 eBPF LESSON 7: Go Integration
// ---------------------------------
// This is the userspace component that:
// 1. Loads the compiled eBPF program into the kernel
// 2. Attaches it to the appropriate hook (tracepoint)
// 3. Reads events from the ring buffer
// 4. Converts them to Go types for the rest of the agent

package ebpf

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"unsafe"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// ExecEvent represents a process execution captured by eBPF.
// This mirrors the 'struct event' in execsnoop.bpf.c
type ExecEvent struct {
	PID         uint32
	PPID        uint32
	GPPID       uint32 // Grandparent PID for correlation chains
	UID         uint32
	GID         uint32
	TimestampNs uint64
	Comm        string // Command name (e.g., "curl")
	ParentComm  string // Parent command name (e.g., "bash")
	Filename    string // Full path to executable
	RetVal      int32
	ArgsSize    int32
	Args        string
}

// Collector manages the eBPF program lifecycle and event reading.
type Collector struct {
	objs      *execsnoopObjects // Generated by bpf2go
	link      link.Link
	linkSys   link.Link
	linkSysAt link.Link
	reader    *ringbuf.Reader
	events    chan ExecEvent
	logger    *slog.Logger
}

// NewCollector creates a new eBPF-based process execution collector.
//
// 🎓 eBPF LESSON 8: Loading eBPF Programs
// ----------------------------------------
// Loading involves several steps:
// 1. Remove memory lock limits (eBPF maps need locked memory)
// 2. Load the compiled eBPF bytecode into the kernel
// 3. Attach the program to the tracepoint
// 4. Set up the ring buffer reader
func NewCollector(logger *slog.Logger) (*Collector, error) {
	if logger == nil {
		logger = slog.Default()
	}

	// 🎓 Step 1: Allow locking memory for eBPF resources
	// The kernel needs to lock memory for eBPF maps (like our ring buffer).
	// Without this, you'll get "operation not permitted" errors.
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("removing memlock limit: %w", err)
	}

	// 🎓 Step 2: Load the eBPF objects (program + maps)
	// loadExecsnoopObjects is generated by bpf2go from our .bpf.c file
	objs := &execsnoopObjects{}
	if err := loadExecsnoopObjects(objs, nil); err != nil {
		return nil, fmt.Errorf("loading eBPF objects: %w", err)
	}

	// 🎓 Step 3: Attach the program to the tracepoint
	// link.Tracepoint attaches our handle_exec function to sched_process_exec
	l, err := link.Tracepoint("sched", "sched_process_exec", objs.HandleExec, nil)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attaching tracepoint sched_process_exec: %w", err)
	}

	// 🎓 Attach syscalls tracepoint to capture execve arguments
	lSys, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TracepointSyscallsSysEnterExecve, nil)
	if err != nil {
		// Log a warning but don't fail, we can still fall back to /proc reading if this fails
		logger.Warn("failed to attach sys_enter_execve tracepoint (arguments may be missed for fast processes)", "error", err)
	}

	// 🎓 Attach syscalls tracepoint to capture execveat arguments
	lSysAt, err := link.Tracepoint("syscalls", "sys_enter_execveat", objs.TracepointSyscallsSysEnterExecveat, nil)
	if err != nil {
		logger.Warn("failed to attach sys_enter_execveat tracepoint", "error", err)
	}

	// 🎓 Step 4: Create ring buffer reader
	// This reads events submitted by bpf_ringbuf_submit() in the BPF program
	reader, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		l.Close()
		objs.Close()
		return nil, fmt.Errorf("creating ring buffer reader: %w", err)
	}

	return &Collector{
		objs:      objs,
		link:      l,
		linkSys:   lSys,
		linkSysAt: lSysAt,
		reader:    reader,
		events:    make(chan ExecEvent, 1000),
		logger:    logger,
	}, nil
}

// Events returns a channel of process execution events.
func (c *Collector) Events() <-chan ExecEvent {
	return c.events
}

// Start begins reading events from the eBPF program.
// Call this in a goroutine.
//
// 🎓 eBPF LESSON 9: Reading Events
// ---------------------------------
// The ring buffer reader blocks until an event is available.
// When the BPF program calls bpf_ringbuf_submit(), the event
// appears here almost instantly (microseconds).
func (c *Collector) Start(ctx context.Context) {
	c.logger.Info("eBPF exec collector started")

	for {
		select {
		case <-ctx.Done():
			c.logger.Info("eBPF exec collector stopping")
			return
		default:
		}

		// Read the next event (blocks until available)
		record, err := c.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				c.logger.Info("ring buffer closed, stopping")
				return
			}
			c.logger.Warn("reading from ring buffer", "error", err)
			continue
		}

		// Parse the raw bytes into our event struct
		event, err := parseExecEvent(record.RawSample)
		if err != nil {
			c.logger.Warn("parsing exec event", "error", err)
			continue
		}

		// Send to channel (non-blocking to avoid backpressure issues)
		select {
		case c.events <- event:
		default:
			c.logger.Warn("event channel full, dropping event")
		}
	}
}

// Close releases all eBPF resources.
func (c *Collector) Close() error {
	c.reader.Close()
	c.link.Close()
	if c.linkSys != nil {
		c.linkSys.Close()
	}
	if c.linkSysAt != nil {
		c.linkSysAt.Close()
	}
	return c.objs.Close()
}

// parseExecEvent converts raw bytes from the ring buffer to ExecEvent.
// The byte layout must match 'struct event' in execsnoop.bpf.c exactly!
// Instead of manual offset parsing, we use the bpf2go-generated struct to handle padding natively.
func parseExecEvent(data []byte) (ExecEvent, error) {
	if len(data) < int(unsafe.Sizeof(execsnoopEvent{})) {
		return ExecEvent{}, fmt.Errorf("event too short: %d bytes", len(data))
	}

	raw := (*execsnoopEvent)(unsafe.Pointer(&data[0]))

	event := ExecEvent{
		PID:         raw.Pid,
		PPID:        raw.Ppid,
		GPPID:       raw.Gppid,
		UID:         raw.Uid,
		GID:         raw.Gid,
		TimestampNs: raw.TimestampNs,
		Comm:        int8ToStr(raw.Comm[:]),
		ParentComm:  int8ToStr(raw.Pcomm[:]),
		Filename:    int8ToStr(raw.Filename[:]),
		RetVal:      raw.Retval,
		ArgsSize:    raw.ArgsSize,
	}

	if event.ArgsSize > 0 && event.ArgsSize <= 1024 {
		// eBPF populates Arg strings with NUL bytes between them (from user argv pointers)
		// We extract the exact written portion of the args buffer
		event.Args = int8ToStrWithNuls(raw.Args[:event.ArgsSize])
	}

	return event, nil
}

// int8ToStr extracts a C string from a fixed-size int8 array (up to the first NUL).
func int8ToStr(arr []int8) string {
	b := make([]byte, 0, len(arr))
	for _, v := range arr {
		if v == 0 {
			break
		}
		b = append(b, byte(v))
	}
	return string(b)
}

// int8ToStrWithNuls extracts a string including internal NUL bytes, up to the slice length.
func int8ToStrWithNuls(arr []int8) string {
	b := make([]byte, 0, len(arr))
	for _, v := range arr {
		b = append(b, byte(v))
	}
	return string(b)
}

// IsAvailable checks if eBPF is supported on this system.
//
// Deprecated: Use compat.RunChecks() for detailed compatibility reporting.
// This remains for backward compatibility but now delegates to the compat package.
func IsAvailable() bool {
	// Quick checks: BTF must exist and we must be on Linux.
	if _, err := os.Stat("/sys/kernel/btf/vmlinux"); err != nil {
		return false
	}
	return true
}

// nullTerminatedString extracts a C string from a byte slice.
func nullTerminatedString(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

// littleEndian provides little-endian byte order functions.
var littleEndian = littleEndianImpl{}

type littleEndianImpl struct{}

func (littleEndianImpl) Uint32(b []byte) uint32 {
	return uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24
}

func (littleEndianImpl) Uint64(b []byte) uint64 {
	return uint64(b[0]) | uint64(b[1])<<8 | uint64(b[2])<<16 | uint64(b[3])<<24 |
		uint64(b[4])<<32 | uint64(b[5])<<40 | uint64(b[6])<<48 | uint64(b[7])<<56
}
