'use client'

import { motion } from 'framer-motion'
import { Cpu, Radio, Server, BrainCircuit, Bell } from 'lucide-react'

const steps = [
  {
    icon: Cpu,
    title: 'Kernel (eBPF)',
    subtitle: 'Linux, Windows & macOS',
    description: 'Hooks into kernel syscall points to capture every process, file, and network event generated by AI agents. Zero overhead — events written to ring buffers.',
    color: '#9333ea',
    glow: 'rgba(147,51,234,0.2)',
  },
  {
    icon: Radio,
    title: 'Collection Agent',
    subtitle: 'Go · TLS 1.3',
    description: 'Reads ring buffers, enriches events with process metadata, and tracks AI agent lineage. Reduces volume while preserving all security-relevant events.',
    color: '#c4b5d9',
    glow: 'rgba(196,181,217,0.15)',
  },
  {
    icon: Server,
    title: 'Detection Engine',
    subtitle: 'AI-Gated Rules',
    description: 'AI-focused detection rules evaluate every agent action in real time. All rules gate on AI process attribution — only agent activity triggers detection, never system daemons.',
    color: '#f0c800',
    glow: 'rgba(240,200,0,0.15)',
  },
  {
    icon: BrainCircuit,
    title: 'AI Analysis',
    subtitle: 'LLM · Agentic Tools',
    description: 'An LLM with agentic tools analyzes AI agent behavior: explains the attack chain, scores risk, reconstructs process trees, and suggests remediation.',
    color: '#00e676',
    glow: 'rgba(0,230,118,0.15)',
  },
  {
    icon: Bell,
    title: 'Alerts & UI',
    subtitle: 'In-app · Slack · Webhook',
    description: 'Real-time alerts delivered in-app, via Slack, or webhook. Full dashboard with incident timeline, process tree visualization, and AI chat.',
    color: '#ff7a2f',
    glow: 'rgba(255,122,47,0.15)',
  },
]

export function Pipeline() {
  return (
    <section id="how-it-works" className="py-28 relative">
      {/* Faint section glow */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse 60% 40% at 50% 50%, rgba(147,51,234,0.03) 0%, transparent 70%)',
        }}
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Heading */}
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <span className="text-xs font-semibold text-[#9333ea] uppercase tracking-widest">
            Architecture
          </span>
          <h2
            className="mt-3 text-3xl sm:text-4xl font-bold text-[#e8dff5]"
            style={{ fontFamily: "'Space Grotesk', sans-serif" }}
          >
            How It Works
          </h2>
          <p className="mt-4 text-[#c4b5d9] max-w-xl mx-auto">
            From kernel event to AI-analyzed incident in under 100ms.
          </p>
        </motion.div>

        {/* Pipeline steps — horizontal on desktop, vertical on mobile */}
        <div className="relative">
          {/* Connecting line (desktop) */}
          <div className="hidden lg:block absolute top-[3.25rem] left-[10%] right-[10%] h-px bg-gradient-to-r from-transparent via-[rgba(147,51,234,0.2)] to-transparent" />

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6 lg:gap-4">
            {steps.map((step, i) => {
              const Icon = step.icon
              return (
                <motion.div
                  key={step.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.1 }}
                  className="flex flex-col items-center text-center group"
                >
                  {/* Icon node */}
                  <div
                    className="relative w-14 h-14 rounded-xl flex items-center justify-center mb-4 transition-all duration-300 group-hover:scale-110"
                    style={{
                      background: `rgba(10,6,18,0.9)`,
                      border: `1px solid ${step.color}30`,
                      boxShadow: `0 0 0 0 ${step.glow}`,
                    }}
                  >
                    {/* Step number */}
                    <span
                      className="absolute -top-2 -right-2 w-5 h-5 rounded-full text-[10px] font-bold flex items-center justify-center"
                      style={{ background: step.color, color: '#0a0612' }}
                    >
                      {i + 1}
                    </span>
                    <Icon className="w-6 h-6" style={{ color: step.color }} />
                  </div>

                  {/* Arrow between nodes (desktop) */}
                  {i < steps.length - 1 && (
                    <div className="hidden lg:block absolute" style={{ top: '1.75rem', left: `${20 * i + 18}%` }}>
                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                        <path d="M3 8h10M9 4l4 4-4 4" stroke="rgba(147,51,234,0.25)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                  )}

                  <h3
                    className="text-sm font-semibold text-[#e8dff5] mb-1"
                    style={{ fontFamily: "'Space Grotesk', sans-serif" }}
                  >
                    {step.title}
                  </h3>
                  <span className="text-[10px] font-mono text-[#6b5a80] mb-3 block"
                    style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                    {step.subtitle}
                  </span>
                  <p className="text-xs text-[#c4b5d9] leading-relaxed">{step.description}</p>
                </motion.div>
              )
            })}
          </div>
        </div>

        {/* Data flow pill */}
        <motion.div
          className="mt-14 mx-auto max-w-2xl"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5 }}
        >
          <div className="glass-card p-4 flex flex-wrap items-center justify-center gap-2 text-xs font-mono text-[#6b5a80]"
            style={{ fontFamily: "'JetBrains Mono', monospace" }}>
            {['Kernel Event', 'eBPF Ring Buffer', 'Agent Batch', 'Sampling', 'Detection', 'Correlation', 'AI Dossier', 'Alert'].map(
              (label, i, arr) => (
                <span key={label} className="flex items-center gap-2">
                  <span className="text-[#c4b5d9]">{label}</span>
                  {i < arr.length - 1 && <span className="text-[rgba(147,51,234,0.3)]">→</span>}
                </span>
              )
            )}
          </div>
          <p className="text-center text-xs text-[#6b5a80] mt-3">
            End-to-end latency &lt; 100ms from kernel event to database
          </p>
        </motion.div>
      </div>
    </section>
  )
}
